version: "3.9"

services:
  db:
    image: postgres:16
    container_name: course_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: online_course_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: course_backend
    restart: always
    volumes:
      - ./backend:/app         # bind mount در زمان اجرای کانتینر
    env_file:
          - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: course_frontend
    restart: always
    volumes:
      - ./frontend:/app                        # Project files (bind mount)
      - npm_cache:/app/.npm-cache
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true                 # Enable file watching in containers
    depends_on:
      - backend

volumes:
  postgres_data:
  npm_cache:



